4.1.2 2024-02-06 07:00:01,388 INFO 140690253674304 - Starting to get apps
4.1.2 2024-02-06 07:00:02,315 ERROR 140690253674304 - Could not make request to Splunk: [HTTP 404] https://127.0.0.1:8089/services/eura_app_list?type=deployment
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/python_upgrade_readiness_app/bin/eura_remote_latest_report.py", line 104, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=self.session_key, method="GET")
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 661, in simpleRequest
    raise splunk.ResourceNotFound(uri)
splunk.ResourceNotFound: [HTTP 404] https://127.0.0.1:8089/services/eura_app_list?type=deployment
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - merged_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_merged/merged_report.json
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_remote/GOEL-Indexer1.json
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - Skipping to write report from indexer: GOEL-Indexer1 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_remote/GOEL-Indexer2.json
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - Skipping to write report from indexer: GOEL-Indexer2 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_remote/GOEL-Indexer3.json
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - Skipping to write report from indexer: GOEL-Indexer3 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - Writing local report as merged report could not be generated.
4.1.2 2024-02-06 07:00:03,123 INFO 140690253674304 - splunk-system-user file does not exists.
4.1.2 2024-02-06 19:00:01,079 INFO 140509209544512 - Starting to get apps
4.1.2 2024-02-06 19:00:01,966 ERROR 140509209544512 - Could not make request to Splunk: [HTTP 404] https://127.0.0.1:8089/services/eura_app_list?type=deployment
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/python_upgrade_readiness_app/bin/eura_remote_latest_report.py", line 104, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=self.session_key, method="GET")
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 661, in simpleRequest
    raise splunk.ResourceNotFound(uri)
splunk.ResourceNotFound: [HTTP 404] https://127.0.0.1:8089/services/eura_app_list?type=deployment
4.1.2 2024-02-06 19:00:02,795 INFO 140509209544512 - merged_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_merged/merged_report.json
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_remote/GOEL-Indexer1.json
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - Skipping to write report from indexer: GOEL-Indexer1 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_remote/GOEL-Indexer2.json
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - Skipping to write report from indexer: GOEL-Indexer2 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/emerald_remote/GOEL-Indexer3.json
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - Skipping to write report from indexer: GOEL-Indexer3 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - Writing local report as merged report could not be generated.
4.1.2 2024-02-06 19:00:02,796 INFO 140509209544512 - splunk-system-user file does not exists.
