4.1.2 2024-02-06 07:00:01,415 INFO 140486666569536 - Could not find synced splunkbase apps so using the constant file
4.1.2 2024-02-06 07:00:01,416 INFO 140486666569536 - splunkbase_path- /opt/splunk/etc/apps/python_upgrade_readiness_app/bin/libs_py3/pura_libs_utils/splunkbaseapps.csv
4.1.2 2024-02-06 07:00:01,441 INFO 140486666569536 - Starting to get apps
4.1.2 2024-02-06 07:00:02,308 ERROR 140486666569536 - Could not make request to Splunk: [HTTP 404] https://127.0.0.1:8089/services/pura_app_list?type=deployment
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/python_upgrade_readiness_app/bin/jura_remote_latest_report.py", line 229, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=self.session_key, method="GET")
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 661, in simpleRequest
    raise splunk.ResourceNotFound(uri)
splunk.ResourceNotFound: [HTTP 404] https://127.0.0.1:8089/services/pura_app_list?type=deployment
4.1.2 2024-02-06 07:00:03,052 INFO 140486666569536 - merged_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_merged/merged_report.json
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_remote/GOEL-Indexer1.json
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - Skipping to write report from indexer: GOEL-Indexer1 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_remote/GOEL-Indexer2.json
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - Skipping to write report from indexer: GOEL-Indexer2 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_remote/GOEL-Indexer3.json
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - Skipping to write report from indexer: GOEL-Indexer3 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - Writing local report as merged report could not be generated.
4.1.2 2024-02-06 07:00:03,053 INFO 140486666569536 - splunk-system-user file does not exists.
4.1.2 2024-02-06 19:00:01,222 INFO 140401711683392 - Could not find synced splunkbase apps so using the constant file
4.1.2 2024-02-06 19:00:01,223 INFO 140401711683392 - splunkbase_path- /opt/splunk/etc/apps/python_upgrade_readiness_app/bin/libs_py3/pura_libs_utils/splunkbaseapps.csv
4.1.2 2024-02-06 19:00:01,249 INFO 140401711683392 - Starting to get apps
4.1.2 2024-02-06 19:00:02,121 ERROR 140401711683392 - Could not make request to Splunk: [HTTP 404] https://127.0.0.1:8089/services/pura_app_list?type=deployment
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/python_upgrade_readiness_app/bin/jura_remote_latest_report.py", line 229, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=self.session_key, method="GET")
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 661, in simpleRequest
    raise splunk.ResourceNotFound(uri)
splunk.ResourceNotFound: [HTTP 404] https://127.0.0.1:8089/services/pura_app_list?type=deployment
4.1.2 2024-02-06 19:00:02,727 INFO 140401711683392 - merged_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_merged/merged_report.json
4.1.2 2024-02-06 19:00:02,727 INFO 140401711683392 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_remote/GOEL-Indexer1.json
4.1.2 2024-02-06 19:00:02,727 INFO 140401711683392 - Skipping to write report from indexer: GOEL-Indexer1 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 19:00:02,727 INFO 140401711683392 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_remote/GOEL-Indexer2.json
4.1.2 2024-02-06 19:00:02,727 INFO 140401711683392 - Skipping to write report from indexer: GOEL-Indexer2 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 19:00:02,728 INFO 140401711683392 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/jquery_remote/GOEL-Indexer3.json
4.1.2 2024-02-06 19:00:02,728 INFO 140401711683392 - Skipping to write report from indexer: GOEL-Indexer3 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 19:00:02,728 INFO 140401711683392 - Writing local report as merged report could not be generated.
4.1.2 2024-02-06 19:00:02,728 INFO 140401711683392 - splunk-system-user file does not exists.
