4.1.2 2024-02-06 16:00:02,567 INFO 140381905200960 - Starting to get apps
4.1.2 2024-02-06 16:00:03,167 ERROR 140381905200960 - Could not make request to Splunk: [HTTP 404] https://127.0.0.1:8089/services/pura_app_list?type=deployment
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/python_upgrade_readiness_app/bin/pura_remote_latest_report.py", line 137, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=self.session_key, method="GET")
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 661, in simpleRequest
    raise splunk.ResourceNotFound(uri)
splunk.ResourceNotFound: [HTTP 404] https://127.0.0.1:8089/services/pura_app_list?type=deployment
4.1.2 2024-02-06 16:00:04,020 INFO 140381905200960 - merged_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/merged/merged_report.json
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/remote/GOEL-Indexer1.json
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - Skipping to write report from indexer: GOEL-Indexer1 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/remote/GOEL-Indexer2.json
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - Skipping to write report from indexer: GOEL-Indexer2 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - remote_file_path = /opt/splunk/etc/apps/python_upgrade_readiness_app/local/remote/GOEL-Indexer3.json
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - Skipping to write report from indexer: GOEL-Indexer3 as it is empty.Trying to fetch result from another indexer
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - Writing local report as merged report could not be generated.
4.1.2 2024-02-06 16:00:04,021 INFO 140381905200960 - splunk-system-user file does not exists.
