2024-02-06 03:13:19,071 INFO [assist::uiassets_modular_input.py] [uiassets_modular_input] [_run] [16680] Supervisor update required, etag="8caf8e0826646505d41e4ce77ea9b72b", url=https://beam.scs.splunk.com/com.splunk.assist.ui/latest/com.splunk.assist.ui-assets.tgz
2024-02-06 03:13:19,136 INFO [assist::uiassets_modular_input.py] [download] [run] [16680] Download command started
2024-02-06 03:13:19,576 INFO [assist::uiassets_modular_input.py] [logging] [log_process_output] [16680] Download will extract, file=/opt/splunk/var/splunk_assist/ui/assets/3dc6619e7e47185bacae57dfacd408ca0dcbffcaddbe0479dc7effc4800e5a41/com.splunk.assist.ui-assets
2024-02-06 03:13:19,576 INFO [assist::uiassets_modular_input.py] [download] [run] [16680] Download command complete, return_code=0
2024-02-06 03:13:19,576 INFO [assist::uiassets_modular_input.py] [config] [_set_app_config] [16680] Updating local node config, key=assets_root, value=/opt/splunk/var/splunk_assist/ui/assets/3dc6619e7e47185bacae57dfacd408ca0dcbffcaddbe0479dc7effc4800e5a41/com.splunk.assist.ui-assets
2024-02-06 03:13:19,592 INFO [assist::uiassets_modular_input.py] [config] [_set_app_config] [16680] Updating local node config, key=etag, value="8caf8e0826646505d41e4ce77ea9b72b"
2024-02-06 09:16:30,042 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [854] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 09:16:30,048 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [854] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
2024-02-06 19:52:33,100 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [28520] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 19:52:33,109 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [28520] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
